### PR TITLE
Fix data import issue

### PR DESCRIPTION
**Pull request by MattPutnam**
It was a problem with the way in which the payload was encoded.  In all other cases we're converting a clojurescript data structure to JSON, so I was doing that by default.  But here we don't want any conversion.  So I added a mechanism to specify how to encode the payload, defaulting to JSON.

Also shoehorning in the "Creating Workflow..." cosmetic bug that Greg noticed since this is a small PR.

### CODE REVIEW

**Comment by MattPutnam** [comment]
Correct.  The `nil` case is the default, i.e. no encoding specified.

**Comment by dmohs** [comment]
Another option for this: The caller specifies `:data` for raw data (which is passed through unchanged) or `:payload` for the thing that will get converted to JSON. Could even rename `:payload` to `:cljs-data`. Good to merge as-is or with this suggested change.

**Comment by MattPutnam** [comment]
Ooh, I like that idea better.

**Comment by dmohs** [comment]
Me too :)

**Pull request merged**
