### PR TITLE
Es dsdeepb 10

### PR DESCRIPTION
**Pull request by eddiebroad**
using the tab component, get method configurations working.
Use mock ajax call.

### CODE REVIEW

**Comment by eddiebroad** [comment]
I think I merged in changes from a branch matt was working on (tab bar) so that my code could use those changes so that the method configurations would appear as a selectable item.

**Comment by rushtong** [comment]
@eddiebroad - this still has conflicts. If you can squash and rebase, that would help.

**Comment by eddiebroad** [comment]
I did do a squash and rebase.

**Comment by eddiebroad** [comment]
I had done a rebase/squash on my local machine(several conflicts were addressed during this) .  Then, at the command line, I tried to push the branch to github. Upon doing so, the command line requested a pull, so I did a pull.  Then, a conflict resulted from that pull.  Once that conflict was resolved, a git push was done. Finally a commit removing a completely unused method was done, then pushed, then the PR was initiated.

**Comment by rushtong** [comment]
There are 46 commits in this PR - whatever happened didn't work out as you expected. I can do the squash later on tonight if you like.

**Comment by eddiebroad** [comment]
for addressing merge conflicts, please let me know and I can sit in during the review and offer any thought, knowledge, etc.

**Comment by eddiebroad** [comment]
if you are going to squash greg, should I sit with you to do so? for offering any information on any conflict that may arise

**Comment by eddiebroad** [comment]
I'm not sure if I correctly pushed the squashed commits or not.   that may be the issue.  Today is the my second squash since David M first showed me the squash maybe two weeks ago.

**Comment by eddiebroad** [comment]
@GregoryRushton  @MattPutnam Please don't hesitate to contact me if you want me to answer any question or concern you have about this PR!

**Comment by MattPutnam** [comment]
It's definitely not squashed and rebased.  I don't know what you did but it seems to look exactly the same as before.

**Comment by eddiebroad** [comment]
I think I may have correctly squashed at my local repository on my laptop, but during a pull or push may somehow have undone it the rebase/squash.

**Comment by eddiebroad** [comment]
If I click on "files changed", the differences in +/- (green/red)  seem to me straightforward to resolve.  The "giant" addition (in green) might be accepted with some changes. BUT....some of the other stuff, some aren't very critical and maybe the master branch might not want the changes. (for example some comments starting with ";;" I put in)

**Comment by eddiebroad** [comment]
this commit represents the squash I did locally : c40bd6db38dd500d1d09eedc08e9df61b9c6acf1

**Comment by MattPutnam** [comment]
That diff is from when you branched.  The problem is that there are new changes on master.  You need to rebase off of origin/master.

**Comment by eddiebroad** [comment]
@MattPutnam , you mean rebase off of origin/master *before* the branch that created DSDEEPB-10 ?

**Comment by MattPutnam** [comment]
No, rebase off the current origin/master.

**Comment by eddiebroad** [comment]
@MattPutnam you mean rebase off the current HEAD of the master?

**Comment by eddiebroad** [comment]
@MattPutnam you mean  off the current origin/master

**Comment by MattPutnam** [comment]
The current, most recent state of the master branch.

**Comment by eddiebroad** [comment]
okay @MattPutnam .  Maybe I can/should close this pull-request, then redo the rebase/squash operation, then, initiate a new PR?

**Comment by MattPutnam** [comment]
You don't have to close the PR, just get the branch fixed and force-push it.

**Comment by eddiebroad** [comment]
okay

**Comment by rushtong** [comment]
I spent some time trying to re-base this, but didn't have any luck. I can only go back so many commits on the current branch before it chokes with an error trying to go all the way back to 46. For reference, one can do a `git rebase -i HEAD~X` where x is the number of commits you want to walk back. There was some kind of weird branching early on that prevents git from being able to handle that command on this branch.

For brevity's sake, I recommend this.
```
git reset --soft 635dd3ea7d0359c27b6ceac8171c0b2f28282c05
```
That will leave all changes for the past 46 commits in place as if you had never committed them. 
Commit that and force push it to the branch. That will overwrite some other authors' commits to this branch, but I think that's a minor issue in comparison. Then, force push that branch to origin, then rebase onto master, OR, merge from master and then force push the newly merged branch.

**Comment by eddiebroad** [comment]
Thank you Greg!!!!!!!!!!!
I went home yesterday and thought of the idea to 1) set aside my current local/working copy of the code (no deletion/modification whatsoever), then 2) re-clone the git rep (fresh master!!!), 3) create a new branch, 4) do a few copy/paste routines from the set-aside repo into the newly created branch, and make sure it works using only a single commit or two, 4) issue a new PR.  What do you think I wonder?  I'm going to try it now....

**Comment by eddiebroad** [comment]
this idea might not be the most ideal, but I want to get work merged into the master as soon as reasonably possible.  At the least, I can take this branch as a learning experience! This is the biggest group/team programming I've ever done and the git workflows/protocols I've never used before.  My previous "git life" was only with 1-2 others...

**Pull request closed without merging**
