### PR TITLE
Editing a method configuration now works.

### PR DESCRIPTION
**Pull request by MattPutnam**
TODO: make a unified orchestration call to do the full update at once

### CODE REVIEW

**Comment by eddiebroad** [comment]
@MattPutnam  does it work when "use-live-data" is set to true? is there a good way to experience the "editing"? does the back-end persistence work do you know Matt?

**Comment by MattPutnam** [comment]
Yes, this should all work.

**Comment by eddiebroad** [comment]
wonderful!

**Comment by dmohs** [comment]
:+1: Code looks good. I like the rename shim for now. Merging since Rawls is down and we can't test.

**Pull request merged**
