### PR TITLE
Disable Publish button for non-Agora configs [GAWB-3105]

### PR DESCRIPTION
**Pull request by aednichols**
~~Requires a version of the API that returns the `sourceRepo` key in the `methodRepoMethod` response, so can't merge until https://github.com/broadinstitute/rawls/pull/854~~

It's not quite possible to full test this until [GAWB-3197](https://broadinstitute.atlassian.net/browse/GAWB-3197) ("call Dockstore instead of Agora when appropriate") because the config detail page is fairly broken; you can load up a Dockstore method like [this one](http://local.broadinstitute.org/#workspaces/broad-dsde-dev/anicholstest/method-configs/adam-methods/dockstore-test) and see that the value of `sourceRepo` is correct and in the right place for this code to find it.

The API side of this is handled in GAWB-3101: https://github.com/broadinstitute/rawls/pull/873/files#diff-053c644d2ec1022a705d40195e018a94R719

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by MattPutnam — COMMENTED** [review]
I think it would be better to hide the button entirely when we can't publish. Our overall philosophy on disabled vs. not present is that if the user can take some action to make the button clickable, then disable it (e.g. unlocking a locked workspace), but if it's fundamentally not possible, then don't show it.

**Comment by aednichols** [comment]
Fair point, in fact, that's exactly what the story says to do.

**Review by MattPutnam — APPROVED** [review]
👍

**Review by davidangb — APPROVED** [review]
:+1: did not test

**Comment by aednichols** [comment]
jenkins retest

**Pull request merged**
