### PR TITLE
some UI for viewing method configurations to import

### PR DESCRIPTION
**Pull request by eddiebroad**
* I added a new tab in the workspaces tab for importing method configurations. this perhaps next be moved to appear as a modal div from a button appearing in the other "Method Configurations" tab
*  I added code that retrieves from a checkbox the status of the checkbox
* this is solely in the UI layer, nothing happens in any other layer

### CODE REVIEW

**Comment by eddiebroad** [comment]
I accidentally named this with the ID  506..... but everywhere you see here 506, it should instead be 878.

**Comment by MattPutnam** [comment]
As we discussed after the standup, this isn't the UI we want.  We eventually want two places to do this: a modal "dialog" (see the "Create Workspace" button) from the Method Configs tab that shows all available configs to select from, and an ability to add from the Method Repository page.

**Comment by eddiebroad** [comment]
Okay Matt.  I had though to rearrange the GUI elements to appear as modal via the "Method Configurations" tab but wasn't sure if I should do so before this PR or not.  I wasn't sure if it's a good idea or not to issue a PR then follow it with another subtask (involving rearranging the GUI elements) with another PR for it.

**Comment by eddiebroad** [comment]
I have created a local branch and am working to get a modal "Select Method Configuration To Import Into Your Workspace" box  to show up...

**Pull request closed without merging**
