### PR TITLE
handle errors in project creation

### PR DESCRIPTION
**Pull request by dvoet**
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by dvoet** [comment]
@dmohs @zarsky-broad Can I hand this off to one of you? This goes along with https://github.com/broadinstitute/rawls/pull/618. I added a message column to the billing project list page along with icons for the various states of a project. There is a new one, Error, in addition to the original Creating and Ready. It all looks ok to me with one problem. When a project is "Creating" the ui polls occasionally to see if it is "Ready". Now there is a new case of "Error" and if an error happens the polling mechanism does not update the message column for that row.

**Comment by dvoet** [comment]
I am not a UX guy, but I hate showing the error message as a tool tip because
- it is not apparent that there is a message, worsened because hover takes too long
- message may be long, not comfortable in a tool tip
- cannot copy/paste them to an error report
- cannot screen shot them either

**Comment by dvoet** [comment]
Also need to exclude Error projects from the project drop down on create and clone workspaces (in  get-billing-projects function I think).

**Comment by dvoet** [comment]
@zarsky-broad LGTM - I made 1 minor change. If you are good I will push all 3 repos.

**Comment by zarsky-broad** [comment]
@dvoet So, sorry, would this make pending projects not appear in the list?

**Comment by dmohs** [comment]
@zarsky-broad Only if `include-pending?` is falsy.

**Comment by dvoet** [comment]
@zarsky-broad the current functionality already excludes pending from the list, the change excludes Error as well. But it actually flips the logic and includes only Ready.

**Review by dmohs — APPROVED** [review]
Just tested. Seems good to go.

**Pull request merged**
