### PR TITLE
GAWB-818 + GAWB-84: Billing Management UI + Display email instead of name 

### PR DESCRIPTION
**Pull request by MatthewBemis**
Sorry for two tickets in one PR, but they were a natural pair since they touched the same part of the UI. GAWB-84 can be seen mostly in commit b62772639477fcc80aa7120589f4188d9e0ad7c7

These visual changes have gotten PO approval 
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] **Submitter**: Tell tech lead that the PR exists if s/he wants to look at it
- [x] **Submitter**: Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [x] **Tech lead**: sign off
- [x] **LR**: sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [x] **Submitter**: Check configuration files in Jenkins in case they need changes
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't 
  working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev server still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
I would prefer to remove the always-disabled "Create New Billing Project" button entirely, and re-add this button once its backend functionality is available. I won't hold up this PR if that's difficult for any reason, like re-flowing the UI.

Otherwise 👍 !

**Comment by MattPutnam** [comment]
^ The existence of the button necessitates a (sadly) nontrivial amount of code, so we should leave it.  We can hide it for now by adding `:display "none"` to the containing div.  I'm going to pick up the story to implement that as soon as this goes in.

**Comment by MattPutnam** [comment]
There's kind of a lot of unused stuff in billing_management.cljs, looks like vestigial stuff from copy/paste.

**Comment by rushtong** [comment]
Nitpick: The dropdown arrow seems overly large to me and is a bit distracting. I would recommend something more closely in line with that font size, or increase the font size to match the arrow size. Here is an example of what I think is a better sizing between text and arrow:
arrow

**Comment by rushtong** [comment]
Nitpick: The button styling around the email address doesn't look like our other buttons. Can we apply the same button treatment we do in other places?

**Comment by rushtong** [comment]
👍  Minor subjective visual feedback, but don't let that hold up the PR. Looks good, works good.

**Comment by MatthewBemis** [comment]
@davidangb @MattPutnam I'll hide the button for now because it's not clear when the APIs for creating a billing project will be done. Matt- do you want to re-enable the button as part of 854?

**Comment by MatthewBemis** [comment]
I've addressed the PR comments.

-Reduced arrow font size from 12px to 8px
-Changed the box shadow to not display above the first item in the dropdown (it would overlap with the email address which was annoying)
-Re-styled the email address button to have a slight border curve (2px to match other buttons), and styled with grey to match filter buttons
-Hid Create New Billing Project button to be re-introduced in GAWB-854

screen shot 2016-07-19 at 11 13 44 am
 screen shot 2016-07-19 at 11 13 48 am

**Comment by rushtong** [comment]
👍 Beautiful!

**Comment by davidangb** [comment]
👍

**Pull request merged**
