### PR TITLE
GAWB-2977: Free Tier Test

### PR DESCRIPTION
**Pull request by rushtong**
Addresses https://broadinstitute.atlassian.net/browse/GAWB-2977
Resubmission of https://github.com/broadinstitute/firecloud-ui/pull/1105

---

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by kyuksel — APPROVED** [review]

**Review by davidangb — APPROVED** [review]
:+1: approving - as long as you can get agreement from Nicole and project team that ignoring the "should not treat non-pet service accounts as pets" test is acceptable.

**Review by aednichols — APPROVED** [review]
👍

~I think our usual flow is to have @ndbolliger enter a ticket for `SamApiSpec`.~

~In this case, I will own this and include the results of the 2:30 Catalog <> Project Team meeting in the ticket.~

We're just going to edit Sam the test so it's no longer problematic

**Comment by aednichols** [comment]
@rushtong the unit tests will not pass until I merge https://github.com/broadinstitute/firecloud-ui/pull/1136 into dev and you merge dev into your branch

The unit test PR is waiting on selenium.

**Comment by rushtong** [comment]
@aednichols - This PR was passing yesterday ... bummer. I'll re-merge when possible.

**Comment by rushtong** [comment]
@jmthibault79 - Please have a look at https://github.com/broadinstitute/firecloud-ui/pull/1135/commits/b6e8f0ff3b046627147554a6caf0fb00d8cc007c
We looked at that test as a team and rewrote it so that it doesn't delete the service account orchestration registers on startup.

**Comment by rushtong** [comment]
jenkins retest

**Comment by jmthibault79** [comment]
That change makes sense.  :+1:

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
Thanks @jmthibault79!

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
Was able to successfully run tests manually against a dev fiab: [gawb-2977-manual-tests.txt](https://github.com/broadinstitute/firecloud-ui/files/1655886/gawb-2977-manual-tests.txt)

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Pull request merged**
