### PR TITLE
Downgrade selenium/node-chrome to 3.8.1-erbium

### PR DESCRIPTION
**Pull request by rtitle**
See if this fixes failing fiab-test runs...

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by breilly2 — APPROVED** [review]
👍

**Review by andy7i — APPROVED** [review]
👍

**Review by aednichols — APPROVED** [review]
Even if we weren't trying to fix something, I like the idea of pinning so the platform is more predictable over time

**Comment by breilly2** [comment]
@aednichols The problem is that this dependency locks in the version of Chrome. Since Chrome auto-updates in the wild, our test environment also has to stay up-to-date to make sure FC doesn't break when people's browsers get updated.

An alternative to always taking the latest version is to lock the version and manually respond to updates. The advantage is that incompatibilities don't immediately affect everyone. The disadvantage is that we have to be very proactive about watching for updates and manually bumping the version after making sure everything works. (This is probably similar to BITS deciding whether or not to vet software updates before letting them automatically roll out to Broadies' computers.)

**Comment by aednichols** [comment]
I thought the Docker way of running Selenium locally controlled the Chrome version. No?

**Comment by breilly2** [comment]
I'm not sure I follow. May need to discuss in person.

We can control the Chrome version used for our tests. We cannot control the Chrome version in the wild which we have to support. Therefore, one way or another, we have to keep our tests running on the latest versions.

**Comment by aednichols** [comment]
It's not important - but I thought you were referring to dev workstations when you said in the wild

**Comment by breilly2** [comment]
Ah, by "in the wild" I meant end-users' computers... but really applies to any workstation since Chrome is pretty aggressive about updating itself.

**Pull request merged**
