### PR TITLE
if the public user has the OWNER setting then change it to READER!

### PR DESCRIPTION
**Pull request by eddiebroad**
no action is taken if the change is to READER or NO ACCESS

### CODE REVIEW

**Comment by MattPutnam** [comment]
We should simply not have that option.  We certainly shouldn't be clobbering the user's choice.

**Comment by eddiebroad** [comment]
Re : "we should simply...."  Can you explain more?  This is for if the user of the ACL is the public.  The main motivation is to prevent the situation where anyone who can log in is granted owner privelege

**Comment by eddiebroad** [comment]
Re: "we should simply...." maybe these sort of things should be occurring in orchestration or in Agora?

**Comment by eddiebroad** [comment]
Re: "we should simply..."  Is it thought that a checkbox for "Make Publicly Readable" would be better?

**Comment by MattPutnam** [comment]
You're providing the user the option to select "OWNER", then yanking it out from under them if they choose it.  Just don't provide the option.

**Comment by MattPutnam** [comment]
Yes, it seems like it's a binary option, so the checkbox sounds like a better idea.

**Comment by eddiebroad** [comment]
Re: "Yes, it seems...." okay this idea I had thought of maybe might be better for consistency with other users.  I will cancel this PR

**Pull request closed without merging**
