### PR TITLE
Created initial footer component

### PR DESCRIPTION
**Pull request by MattPutnam**
Possibly a bit overengineered, but I was reminded of an annoyance at my previous job--every year there would be a stupid bug report to fix all of the copyright years in about 80 places.

### CODE REVIEW

**Comment by rushtong** [comment]
Showoff!

**Comment by rushtong** [comment]
:+1: Merging.

**Comment by dmohs** [comment]
Nicely done. One question for you and the team: For unicode characters, I tend to just put the character directly in my file. In this case, I would paste in © from somewhere rather than use the escape sequence ("\u00A9"). Any thoughts for a standard style for us?

**Comment by rushtong** [comment]
In general, I try to use html entities. I probably should have called that out. Not sure if there are clojure syntax conflicts with & - it would be good to have an informed choice.

**Comment by dmohs** [comment]
There are no problems in Clojure, but adding these in React is a pain in the neck. If we need to do this, I'll be happy to provide an example.

**Pull request merged**
