### PR TITLE
[GAWB-2056] The status of the last run is showing green when there ar…

### PR DESCRIPTION
**Pull request by rtitle**
…e errors in them

https://broadinstitute.atlassian.net/browse/GAWB-2056

Not sure why string keys were being used here - the map lookups were returning `nil`. Using keywords fixes the issue. Also put keywords before the map, as that seems to be the convention.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by rtitle** [comment]
@dmohs want to check this out, make sure it makes sense?

**Review by dmohs — APPROVED** [review]
A while back we converted some of our AJAX calling code to convert from strings to keywords, so that could explain these string keys. Thanks for fixing!

**Comment by rtitle** [comment]
Np, thanks for reviewing.

For next beer hour: I submit that this bug would not be possible in a strongly-typed language, since getting a map with the wrong key type would be a compile error :)

**Comment by dmohs** [comment]
I submit that this isn't a very interesting discussion :) Of course that is true. The interesting bit is around, "is it worth it?" Now that I'm happy to dig into!

**Comment by rtitle** [comment]
Fair enough :)

**Pull request merged**
