### PR TITLE
Convert spinners and blockers (no JIRA)

### PR DESCRIPTION
**Pull request by MattPutnam**
These don't need to be React components, and it's easier to create them now too.

With the spinner, it turns out there were several old usages that were attempting to pass CSS properties to the component that weren't doing anything. I just got rid of these.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [x] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by zarsky-broad** [comment]
I fundamentally agree with this, but I'm not in love with having functions with noun names. I'd feel more comfortable with something like `spinner/create` or `blocker/render`

**Comment by aednichols** [comment]
I overheard your guys' conversation, and I would have to say I like noun-only names a lot, they feel true to the simplicity of Clojure.

To me, `spinner/create` sounds like you're calling a factory method on the `spinner` class that returns a new instance of itself - totally different programing paradigm.

**Review by davidangb — APPROVED** [review]
:+1: looks like a good change. I did not test and only gave this high-level TL review; counting on other reviewers to find any low-level syntax or functional problems.

**Comment by davidangb** [comment]
jenkins retest

**Review by zarsky-broad — APPROVED** [review]
Bah, I may be grumpy about parts of this, but it's definitely an improvement over the current situation. I say merge it.

**Pull request merged**
