### PR TITLE
Fixed UI code to conform to new Rawls response.

### PR DESCRIPTION
**Pull request by MattPutnam**
Also fixed mock data, create workspace, and added a blocker during workspace creation.

### CODE REVIEW

**Comment by eddiebroad** [comment]
Have you tested this code running with RAWLS? If yes, did it run correctly?

**Comment by MattPutnam** [comment]
It was working earlier today.  Looks like they're currently switching the domain names so this is broken again.

**Comment by eddiebroad** [comment]
re: "It was working earlier today."  in that case, I think it can and perhaps should be merged.  Do you agree?

**Comment by MattPutnam** [comment]
Sure.  We'll have to change some URLs but that's a separate issue.

**Comment by eddiebroad** [comment]
re: "Sure" , okay, I plan to merge.  Do you explicitly confirm that you have no objection to that?

**Comment by MattPutnam** [comment]
Yes

**Pull request merged**
