### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by rushtong**
Looks like the underlying json is not what it was originally. Updated component to look for the right json element and added new success case.

### CODE REVIEW

**Comment by MattPutnam** [comment]
Is "Succeeded" still being used?  If not, let's get rid of it, otherwise :+1:

**Comment by rushtong** [comment]
I don't think it's possible to tell from the code if "Succeeded" is something that we get back from one of the various json structures. I left it as is so I wouldn't break some other parsing that I am unaware of. One of the downsides of not using enum-like structures.

**Comment by MattPutnam** [comment]
I'm confused, looking at Rawls it's still "Succeeded".  Whatever the case, we also need to change `all-success?` above.

**Comment by rushtong** [comment]
Now I'm confused. The bit of json that comes back and generates the incorrect icon is:
```
"backendStatus": "Success"
```
There is *also* a "Succeeded" elsewhere in the json, but that's not what's causing the specified bug. Here is a full version for reference:
```
{
  "calls": {
    "CancerExomePipeline_v2.M2": [{
      "executionStatus": "Done",
      "stdout": "gs://rawls-e7013b8e-06bf-459e-a3c8-af73aff47665/5c5d585d-f05a-49ad-bffa-302b673c115c/CancerExomePipeline_v2/110e4cbe-1468-47fa-862b-d64e8e660e14/call-M2/job.stdout.txt",
      "backendStatus": "Success",
      "shardIndex": -1,
      "outputs": {
        "m2_output_vcf": "gs://rawls-e7013b8e-06bf-459e-a3c8-af73aff47665/5c5d585d-f05a-49ad-bffa-302b673c115c/CancerExomePipeline_v2/110e4cbe-1468-47fa-862b-d64e8e660e14/call-M2/mutations.vcf"
      },
      "inputs": {
        "ref_fasta": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta",
        "tumor_bai": "gs://cancer-exome-pipeline-demo-data/HCC1143_BL.100_gene_250bp_pad.bai",
        "tumor_bam": "gs://cancer-exome-pipeline-demo-data/HCC1143_BL.100_gene_250bp_pad.bam",
        "intervals": "gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list",
        "m2_output_vcf_name": "mutations.vcf",
        "ref_fasta_fai": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.fai",
        "normal_bam": "gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bam",
        "normal_bai": "gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai",
        "ref_fasta_dict": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict"
      },
      "returnCode": 0,
      "jobId": "operations/EKmW18mVKhiZgM7F1tTIn2Ugw7vetLsXKgpwcm9kdWN0aW9u",
      "backend": "JES",
      "end": "2015-11-30T16:33:12.000Z",
      "stderr": "gs://rawls-e7013b8e-06bf-459e-a3c8-af73aff47665/5c5d585d-f05a-49ad-bffa-302b673c115c/CancerExomePipeline_v2/110e4cbe-1468-47fa-862b-d64e8e660e14/call-M2/job.stderr.txt",
      "start": "2015-11-30T16:24:36.000Z"
    }]
  },
  "outputs": {

  },
  "id": "110e4cbe-1468-47fa-862b-d64e8e660e14",
  "inputs": {
    "CancerExomePipeline_v2.M2.intervals": "gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list",
    "CancerExomePipeline_v2.M2.tumor_bam": "gs://cancer-exome-pipeline-demo-data/HCC1143_BL.100_gene_250bp_pad.bam",
    "CancerExomePipeline_v2.M2.normal_bam": "gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bam",
    "CancerExomePipeline_v2.M2.ref_fasta_dict": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict",
    "CancerExomePipeline_v2.M2.tumor_bai": "gs://cancer-exome-pipeline-demo-data/HCC1143_BL.100_gene_250bp_pad.bai",
    "CancerExomePipeline_v2.M2.normal_bai": "gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai",
    "CancerExomePipeline_v2.M2.ref_fasta": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta",
    "CancerExomePipeline_v2.M2.ref_fasta_fai": "gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.fai",
    "CancerExomePipeline_v2.M2.m2_output_vcf_name": "mutations.vcf"
  },
  "submission": "2015-11-30T16:24:35.000Z",
  "status": "Succeeded",
  "end": "2015-11-30T16:33:12.000Z",
  "start": "2015-11-30T16:24:35.000Z"
}
```
Will look at the all-success too.

**Comment by rushtong** [comment]
@MattPutnam - I don't think my last commit makes any visible difference (I think there's a different code path for workspace status vs call status), but it makes sense from a consistency perspective to check for "Success" as well.

**Pull request merged**
