### PR TITLE
GAWB-2900 and 3146: Handle persisted columns that no longer exist

### PR DESCRIPTION
**Pull request by MattPutnam**
Here's what happened to cause both of these tickets:

1. Some data was imported that had more attributes than were already present
2. Those attributes got persisted into table state storage
3. The extra data (and attributes) were deleted via API
4. Now, when trying to load the table, the storage caused the Table component to create columns for attributes that didn't exist
5. Those extra column definitions didn't have a valid renderer, causing a Javascript error

To reproduce yourself, you can simply edit any table state in your local storage and add a bogus column, then try to reload.

To fix this, table state restoration now checks for extra columns in storage that don't exist in the column definitions. If any are present, it eliminates them and also re-saves the repaired columns.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [x] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by davidangb — APPROVED** [review]
This looks like it does the right thing, and code is nice and small. I didn't test it manually myself. Will talk offline about testing. :+1:

**Comment by MattPutnam** [comment]
jenkins retest

**Comment by MattPutnam** [comment]
One failure:
```
WorkspaceSpec:
[info] A user
[info]   who owns a workspace
[info]   - should not be able to set/change can compute permissions for other owners *** FAILED ***
```
This is a modal thing that's fixed in my other PR. Nicole has given the go-ahead to merge.

**Review by zarsky-broad — APPROVED** [review]
I'm not in line with exposing the persistence key like this, but I certainly don't have a better idea.

**Review by davidangb — APPROVED** [review]
still :+1:

**Pull request merged**
