### PR TITLE
Style guide draft

### PR DESCRIPTION
**Pull request by dmohs**
https://broadinstitute.atlassian.net/browse/GAWB-1466

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [x] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by MattPutnam** [comment]
To the thing about state changes being asynchronous, add some suggestions for how to avoid:

```clojure
;; instead of:
(swap! state assoc :foo (bar ...))
(some-func (:foo @state))
;; try:
(let [new-value (bar ...)]
  (swap! state assoc :foo new-value)
  (some-func new-value))

;; instead of:
(react/call :some-state-modifying-method this)
(some-func (:some-key @state))
;; try:
(react/call :some-state-modifying-method this)
(after-update #(some-func (:some-key @state))))
```

---

I seem to have screwed up my IntelliJ clojure formatting settings and can't figure out how to get them back.  As part of this PR, can someone who's configured properly export their settings so that others can just import them?

**Comment by dmohs** [comment]
@MattPutnam I exported my own settings and added them to this PR. See if importing those fixes your issues.

**Comment by dmohs** [comment]
Dear self: Please add a note about disabling the cache in Chrome when devtools is open.

**Comment by zarsky-broad** [comment]
screen shot 2017-01-06 at 11 04 31
Another note to @dmohs.

**Comment by dmohs** [comment]
disable cache image

**Comment by dmohs** [comment]
Calling this done. We should own this document together, so if you have additional comments or suggestions, please make the changes yourself and open a PR.

**Pull request merged**
