### PR TITLE
don't auto-show nps survey

### PR DESCRIPTION
**Pull request by zarsky-broad**
Co-Authored-By: Joe BuAbbud <jbuabbud@users.noreply.github.com>

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
Could you explain the reasoning behind this PR? If this is a request from comms/PO, okay - otherwise we should not do this. This will inhibit comms' ability to control when the survey is visible, because this PR will not always load the surveymonkey JS.

**Comment by zarsky-broad** [comment]
The main concern is that auto-displaying a survey on login is generally a good way to have people either dismiss it, or give unduly negative responses, because they are annoyed at having a modal show up when they logged in to do some work. This way, people have the chance to opt-in, and we're more likely to get feedback from people that's accurate. Ilyana okayed this change; the main reason I really want to get it in is that I feel like an auto-popup is antagonizing users, and especially with recent prod issues, I don't want them to feel like we're trying to get in their way or anything like that.

**Comment by ghost** [comment]
I've gotten the go-ahead from PO and Comms to move forward with this approach.

**Comment by ghost** [comment]
build failure unrelated to tests - jenkins retest

**Review by ghost — APPROVED** [review]

**Review by davidangb — COMMENTED** [review]
:+1: for code/syntax. I ran it quickly but didn't do extensive functional testing.

Before fully approving, there's a corner case to think about. Consider a user who has previously responded to or dismissed the survey. This user will have cookies written, in (I believe) the surveymonkey.com domain. Next, the user clears browser data for the firecloud.org domain. Upon revisiting FC, this user will see the comment icon, but clicking on it will do nothing. Under the covers, we are showing the comment icon because *our* persistence key is gone, but when the surveymonkey JS runs, it finds its cookie and shows nothing.

Those of us developers who have already seen the survey are likely to encounter this. End users in prod are less likely, but possible. Thoughts?

**_Update:_** if we release the v1 UX to prod (as looks likely), many end users will encounter this corner case.

**Comment by davidangb** [comment]
and @zarsky-broad thanks for the explanation! We had a bunch of discussion outside this comment thread, and since comms + PO like this approach, I'm good with it.

**Comment by zarsky-broad** [comment]
We could potentially check for the `CX_xxxxxxxxxx` cookie, apparently that's the one that controls if it's been seen?
https://help.surveymonkey.com/articles/en_US/kb/About-the-cookies-we-use
The problem is, I don't know if it's just its presence, or based somehow on its value. It hows up in `document.cookie`, though.

**Comment by ghost** [comment]
@davidangb i haven't been able to produce the corner case you mentioned. could you maybe explain how a user would do that?

**Comment by zarsky-broad** [comment]
@jbuabbud try deleting the local storage entry, but not the relevant cookies.

**Comment by zarsky-broad** [comment]
It might be best to release this as-is in the name of better than nothing, and address the corner case later.

**Comment by ghost** [comment]
thanks @zarsky-broad

**Comment by davidangb** [comment]
I worry about trying to reverse-engineer their cookies, even though they list them - what if they change in 2 weeks? Also there's something more than that - simply deleting cookies doesn't always make the survey reappear for me. On a longshot, let's see if there's anything in the SM API we can use to help us here.

**Comment by ghost** [comment]
I discussed the corner case with our PO @irosenbe and she has given approval to move forward.

**Comment by zarsky-broad** [comment]
Of note, now that this is in the wild the corner case is everyone who has logged into firecloud since the release. By the time the next release happens, it may as well be everyone. It may be too late for this, although I don't presume to be the one to make that call.

**Comment by dmohs** [comment]
Is it even possible to read the Survey Monkey cookies by code that is served from our own domain?

**Comment by zarsky-broad** [comment]
They're not marked as http-only, so they show up in the `document.cookie` string.

**Comment by davidangb** [comment]
5 failures at https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8616/; investigating ... 
```
[info] *** 5 TESTS FAILED ***
[error] Failed: Total 125, Failed 5, Errors 0, Passed 120, Ignored 5
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec
[error] 	org.broadinstitute.dsde.firecloud.test.library.DataLibrarySpec
[error] 	org.broadinstitute.dsde.firecloud.test.metadata.DataSpec
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainGroupSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1213 s, completed Aug 15, 2018 5:08:52 PM
```

**Comment by davidangb** [comment]
manual runs passed:
MethodLaunchSpec
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8630/
DataLibrarySpec
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8631/
DataSpec
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8635/
AuthDomainGroupSpec
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8633/

**Comment by davidangb** [comment]
I'd love to see the full suite pass: jenkins retest

**Comment by davidangb** [comment]
selenium hub startup errors. one more time: jenkins retest.

**Pull request merged**
