### PR TITLE
bump to 20 minutes

### PR DESCRIPTION
**Pull request by rushtong**
BillingSpec failures are frequently due to timeouts. Bumping to 20 minutes.

Some recent examples:
* https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-test/2018/consoleFull
* https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-test/2016/consoleFull
* https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-test/2015/consoleFull

Example failure:
```
[info] BillingSpec:
[info] A user
[info]   with a billing account
[info]   - should be able to create a billing project *** FAILED ***
[info]     org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.broadinstitute.dsde.firecloud.test.WebBrowserUtil$await$$anon$1@446e3cdb (tried for 30 second(s) with 500 MILLISECONDS interval)
[info] Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
[info] System info: host: '3f197175d2f0', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.11.6.el7.x86_64', java.version: '1.8.0_111-internal'
```

---

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by aednichols — APPROVED** [review]
👍

**Review by andy7i — COMMENTED** [review]
I'm concerned about making the tests run even longer. Do we expect google to take longer than 10+ minutes to create a BP?

**Review by andy7i — APPROVED** [review]
Approving this for now, because we want the tests to pass. We'll see if this makes a big difference in passing and/or test duration.

**Comment by jmthibault79** [comment]
I can confirm that I'm occasionally seeing 10-min BP creation failures.  I made a ticket to investigate: https://broadinstitute.atlassian.net/browse/GAWB-3078

**Pull request merged**
