### PR TITLE
Workspace sharing autocomplete

### PR DESCRIPTION
**Pull request by ghost**
- [x] Merge after [firecloud-orchestration PR 663](https://github.com/broadinstitute/firecloud-orchestration/pull/663)

This is the UI work for [firecloud-app#34](https://app.zenhub.com/workspace/o/databiosphere/firecloud-app/issues/34). The workspace ACL editor now suggests emails from the list of users with whom current user has previously shared a workspace.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [ ] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [x] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [x] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by ghost** [comment]
screen shot 2018-07-27 at 2 11 51 pm
screen shot 2018-07-27 at 2 11 38 pm

**Comment by davidangb** [comment]
It looks like this *replaces* the group autocomplete with the share autocomplete - I had thought the shares were to be *in addition* to the groups.

**Comment by ghost** [comment]
I had it differently in my head but I believe you are correct. Will merge the two lists!

**Comment by ghost** [comment]
Updated to autocomplete from the user's groups in addition to the sharee list.

screen shot 2018-07-30 at 12 00 35 pm

**Review by davidangb — APPROVED** [review]
:+1: looks good - did not test!

**Pull request merged**
