### PR TITLE
Add gs-dowload dialog to the task input/output display.

### PR DESCRIPTION
**Pull request by rushtong**
To test, you will need a successfully run submission. I can share my OncotatorTestClone workspace with anyone that wants to see it.

### CODE REVIEW

**Comment by davidangb** [comment]
This is mostly working for me. However, it changes the UI layout of the input/output display. Previously, the keys and values were on the same line; now the value (i.e. the link) is on a new line, and I think it looks worse.

This is happening because the dialog/GCSFilePreviewLink automatically wraps the link in a div. At minimum, I suggest modifying (defc GCSFilePreviewLink ) to use a span at line 94 instead of a div, to prevent wrapping. The only other place GCSFilePreviewLink is used, I think, is in the entity table, and a span should not cause a regression. A more ideal solution would be to allow callers of GCSFilePreviewLink to pass in CSS styling, and have the input/output display pass in {:display "inline"}.

Finally, how about adding the GCSFilePreviewLink to the stderr/stdout links in CallDetail?

**Comment by rushtong** [comment]
All good points - will revise.

**Comment by rushtong** [comment]
Moving stdout and stderr to full links makes the screen look a little less consistent. I think those two links should be moved to the Output section so they display similarly to the others.

Screenshot:
screen shot 2015-12-03 at 2 09 44 pm

**Comment by davidangb** [comment]
Looks good/works good. Only tweak I see - and I should have called this out earlier - is that by losing the download="stderr" and download="stdout" attributes on the stdout/stderr links, the names of the downloaded files are now different (and much longer). Is this something we care about? I like the long, explicit names - harder to confuse between jobs - but they might be too long.

**Pull request merged**
