### PR TITLE
chet the PO requested these changes

### PR DESCRIPTION
**Pull request by eddiebroad**
for these 6 fields to be in the view for selecting an MC to import

### CODE REVIEW

**Comment by MattPutnam** [comment]
It would be nice to parse the date into something more readable, but otherwise :+1:

**Comment by eddiebroad** [comment]
@MattPutnam  is there a particular column which deserves additional parsing?  My thinking is that the synopsis field column content might eventually get some text area or be bigger ... any such change might depends on the size of the contained text.

**Comment by MattPutnam** [comment]
The created date column.  And actually, I didn't notice this at first, but the label would be "Created Date", not "Create Date".  Still :+1: as-is though.

**Comment by eddiebroad** [comment]
This didn't show up via the hot-related, but when I reloaded from the begining I see an extra column on the right....I'm not sure if that's from this PR or if it's from the table v2?  Do you see it?

**Pull request merged**
