### PR TITLE
filter as you type

### PR DESCRIPTION
**Pull request by MattPutnam**
Still up for debate whether or not we actually want this functionality.  I don't really like it.

### CODE REVIEW

**Comment by eddiebroad** [comment]
What does it mean "filter as you type"?  I hit keys, letter-by-letter, but had to press enter in order to observe filtering

**Comment by MattPutnam** [comment]
Clean your build.  Enter doesn't even do anything any more.

**Comment by dmohs** [comment]
:+1: Do you have a sense about how many rows this can support before performance becomes an issue?

**Comment by MattPutnam** [comment]
It seems to get noticeably laggy around 5000 entries on the method configs tab.  Each table is going to be a bit different though.

**Comment by dmohs** [comment]
Thanks for the performance data. Let's discuss this with Kristian before merging.

**Comment by davidangb** [comment]
I spoke to Kristian about this. Let's push this out past FireCloud v1 MVP.

**Pull request closed without merging**
