### PR TITLE
GAWB-1443: use appropriate auth token for IGV

### PR DESCRIPTION
**Pull request by davidangb**
This is fallout from the login/logout/oauth refactor. In IGV, we were attempting to use an auth token from your cookie - but we no longer write that cookie in all cases. Fix is to use the auth token from the Google library instead.

I've also removed the `get-access-token-cookie` function, so we won't try to call it again in the future.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
Dunno who's working today - @ansingh7115 , @jmthibault79 , @dmohs could I get a review? Who's tech-leading for analysis team - anyone claim TL for this too?

**Review by dmohs — APPROVED** [review]
Definitely the right fix. Great to remove the offending `get-access-token-cookie` function too.

**Comment by breilly2** [comment]
There's still `set-access-token-cookie` and `delete-access-token-cookie`. `delete-` is only called from `set-`, but `set-` is called from a few places in code. It's probably worth auditing those to make sure they can be removed as well.

**Comment by davidangb** [comment]
I don't think `set-access-token-cookie` (and, therefore, `delete-access-token-cookie`) should be removed. It's still used for downloading GCS objects in the `/cookie-authed/download/b/{bucket}/o/{object}` endpoint.

**Comment by breilly2** [comment]
Right, and FCtoken is read in orchestration. Got it. On the surface, it seemed weird to leave calls to a setter for a something that isn't read, but the read is elsewhere.

**Pull request merged**
