### PR TITLE
filter library project from url [SATURN-881]

### PR DESCRIPTION
**Pull request by zarsky-broad**
This allows any number of project names to be specified in the query string in the url when visiting the data library. Upon loading the page the filters are applied when the data loads, overriding any that were persisted, ~~and then removed from the url~~. If there are any other query parameters, they are preserved.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by davidangb — CHANGES_REQUESTED** [review]
this relies on a comma-delimited list of projects in a single query param:
```
https://portal.firecloud.org/?projects=TCGA,TOPMed#library
```
While technically feasible, we will run into nasty complexities if a project name itself contains a comma  -  and in general, working with delimited strings is less clean than working with e.g. arrays.

I suggest instead moving to multiple query params:
```
https://portal.firecloud.org/?projects=TCGA&projects=TOPMed#library
```
(rename "projects" to "project" as desired)
and then use `URLSearchParams.getAll` instead of and then use `URLSearchParams.get`, and loop through the array instead of splitting on a comma.

**Review by davidangb — APPROVED** [review]
:+1:

this *does* allow a user to specify a project that doesn't exist, e.g. http://local.broadinstitute.org/?project=nonexistent+L337+H4x0r#library

that's a bigger fix and raises UX questions about what we *should* do in this feature ... I'm fine merging as-is.

**Comment by zarsky-broad** [comment]
@davidangb Yeah, for the time being I'm calling that out of scope, pending product.

**Comment by zarsky-broad** [comment]
Ok @davidangb, last time. Talked with product; to avoid clobbering a user's saved filter, we won't remove the query string from the URL. When it's present, we won't persist filters, either.

**Review by davidangb — APPROVED** [review]
:+1: I'm fine with this if PO is. There's still some weird UX - which admittedly is tricky to resolve - for instance: 
* nav to a specific project, i.e. /?project=TCGA&return=terra#library
* manually uncheck TCGA in the left nav
* reload page; TCGA is now re-selected

but again, I'm ok with this

**Pull request merged**
