### PR TITLE
[No ticket] Docker image security scan

### PR DESCRIPTION
**Pull request by zbedo**
This PR introduces:

- Docker image security scan, if there are CRITICAL findings, job will fail.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by zarsky-broad** [comment]
I'm not sure that this script is ever used? Also, I'm no longer on the UI team, you might want to tag someone from there.

**Comment by zbedo** [comment]
@zarsky-broad It is used for [firecloud-ui-build](https://fc-jenkins.dsp-techops.broadinstitute.org/view/Build/job/firecloud-ui-build/) in Jenkins.

**Comment by davidangb** [comment]
@zbedo sorry to keep bouncing you around. The Terra UI team (Saturn team) owns firecloud-ui now. @breilly2 is DL there, and could hopefully help you find a reviewer.

**Comment by zbedo** [comment]
Thank you @davidangb ! I checked with @adrazhi and we may not have to integrate it here. Will close this PR for now.

**Pull request closed without merging**
