### PR TITLE
First pass using error viewer and field validation

### PR DESCRIPTION
**Pull request by MattPutnam**
Used in:
* Method config importer: "Save as" field validation, displaying of error messages
* Workspace ACL: Validate that ID field is a valid email address, display of error messages
* Workspace delete: Used Dialog component, which houses potential errors
* Data tab -> delete: "Please select at least one entity" now displays in the dialog, along with potential errors
* Launch analysis: "Please select an entity" now displays in the dialog, along with errors

Subtasks for the remainder of DSDEEPB-1906 have been created

### CODE REVIEW

**Comment by dmohs** [comment]
Please rebase—I'd like to review this in the context of #303.

**Comment by MattPutnam** [comment]
Rebased, but I'm not sure if I did the merge right in summary/tab.cljs.

**Comment by dmohs** [comment]
Thanks for the separate commits—made this manageable. The copied state in ACLs may not be your fault, but let's clean it up as part of this PR. Copied state causes difficult-to-debug problems.

**Comment by MattPutnam** [comment]
This PR and another are stepping on each other pretty hard, so I'd like to not make further changes to this.  I'll add the ACL state thing as a separate story.

**Comment by dmohs** [comment]
Sounds good to me.

**Pull request merged**
