### PR TITLE
Fix GCS links showing pieces in wrong order [GAWB-2495, GAWB-1912]

### PR DESCRIPTION
**Pull request by aednichols**
I can't believe this actually works, but it does. (At least in Chrome.)

---

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by MattPutnam** [comment]
Does this cover all cases? Looks like we should need it on the next line too. And also for DOS files?

**Comment by aednichols** [comment]
The problem only seems to happen when the text fits the pattern `<number>.<something`.

`gs://asdf/4.jpg` is fine, so is `a1.jpg` - and DOS files seem to always display the full URI.

I'll test it some more tomorrow.

**Comment by aednichols** [comment]
Tests failed because we added an extra (non-printable) character and Selenium looks for an exact thing

**Comment by MattPutnam** [comment]
Would this work via `[:span {:style {:textDirection "ltr"}} ...]` instead?

**Comment by jmthibault79** [comment]
Does this also cover GAWB-1912 ?

**Comment by aednichols** [comment]
I think so. I'll check out the A/C and repro steps on 1912 and close it if possible.

**Review by MattPutnam — APPROVED** [review]
I'm skeptical of this being 100% correct, but it seems more correct than before at least.

**Comment by aednichols** [comment]
@MattPutnam tried that, seemed to have no effect; also tried `[:div {:style {:direction "ltr"}} ...]` which fixed the order but broke the ellipsis

**Comment by aednichols** [comment]
jenkins retest because my last test run was expunged from Jenkins

**Comment by aednichols** [comment]
@MattPutnam: the weirdness continues.

The above commit fixes the bug from [GAWB-1912](https://broadinstitute.atlassian.net/browse/GAWB-1912).

The leading `&lrm;` I put in originally is _not_ sufficient to fix the quote being teleported to the start of the string. Maybe at some stage of parsing - possibly influenced by quotes - we are reading from right-to-left, so that's where the control character has to be in order to apply to the whole line?

I tested that ellipsis still works, `5.png` still works, and obviously that the quote is no longer teleported. Removing the leading `&lrm;` re-breaks `5.png`, so both are necessary.

**Comment by jmthibault79** [comment]
Fancy!  How about making this a function?  Something that can be invoked like `(lrm-escape mystring)`

**Review by jmthibault79 — APPROVED** [review]

**Review by rushtong — APPROVED** [review]
👍 Very nice!

**Review by davidangb — APPROVED** [review]
:+1: did not test myself, but looks like a good hack. Nice job!

**Pull request merged**
