### PR TITLE
[DDO-2912] Migrate Firecloud UI configs out of firecloud-develop

### PR DESCRIPTION
**Pull request by choover-broad**
The goal of this PR is to do **the minimal amount of work** to migrate the existing Firecloud UI local development configuration out of firecloud-develop.

Under the existing process, developers clone firecloud-develop and run `render-configs.sh`, which populates the `configs` subdirectory with configuration files and secrets, as well as a script called `docker-rsync-local-ui.sh`, which can be run to spin up a local Firecloud UI server inside a container.

This PR replaces the firecloud-develop step with a new helper script, `local-dev/bin/render`, that **generates the same set of files**. The [`render` tool](https://github.com/broadinstitute/firecloud-develop-shim) generates 3 types of configuration files, giving it approximate parity with firecloud-develop's `configure.rb`:
* secrets pulled from Vault (declared in `local-dev/secrets.yaml`)
* flat configuration files (checked in under `local-dev/templates` without a `.ctmpl`  extension)
* consul templates (checked in under `local-dev/templates` with a `.ctmpl` extension)

### Testing

I was not able to get Firecloud UI running locally! The docker-rsync-local-ui.sh script hangs after logging:
```
Launching Clojure docker container...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
I suspect it's because the existing Docker images do not support ARM. Hopefully someone on the Workflows team can help with testing.

### Modified files

A diff on the files generated by the old process and the new process showed the following delta:

#### config.json
```
Files config/config.json and config.from-fc-dev/config.json differ
diff -r -w -b -B config/config.json config.from-fc-dev/config.json
1a14,15
>
>
8a29,30
>
>
```
This difference is whitespace-only.

#### docker-compose.yaml
```
Files config/docker-compose.yaml and config.from-fc-dev/docker-compose.yaml differ
6a7
>     - ./ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt
```

I removed the ca-bundle.crt file. It is no longer used in live environments, which have certs provisioned by cert manager, and is not necessary for the browser to trust the local.broadinstitute.org cert.

#### local.broadinstitute.org cert & key
```
Only in config: server.crt
Only in config: server.key
```
These files are the `local.broadinstitute.org` cert & key pair located at `secret/dsde/firecloud/local/common`. They were removed from firecloud-develop configs for by https://github.com/broadinstitute/firecloud-develop/pull/3326, which broke TLS for some services. This PR adds them back.

### Related

* https://github.com/broadinstitute/firecloud-develop/pull/3386 will be merged after this PR to prevent confusion (i.e. people updating old files that are no longer used)
-----
- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by knapii-developments — APPROVED** [review]

**Comment by aednichols** [comment]
My saved command for generating configs the old way is
```
( cd ~/Projects/firecloud-develop \
    && git pull \
    && APP_NAME=firecloud-ui \
          RUN_CONTEXT=local \
          ENV=dev INPUT_DIR=. \ 
          OUTPUT_DIR=~/Projects/firecloud-ui/config ./configure.rb )
```

I temporarily modified the repo's `.gitignore` for testing and committed the old config files.
```
*.log
configure.rb
# /config/
```

I then ran `./local-dev/bin/render` and found changes in 3 files identical to the ones you list – and they look reasonable/expected.

I also confirmed that `./config/docker-rsync-local-ui.sh` starts the local server as expected. I did not test any of the optional environment variables. Looks reasonable to me, I doubt the error is related to the change:

Screenshot 2023-06-20 at 16 25 48

**Review by aednichols — APPROVED** [review]
LGTM 👍 

How do I render configs from a personal non-`develop` branch of `firecloud-develop`? Realizing full well that those terms will change but the goal persists. Not a blocker tho.

**Comment by choover-broad** [comment]
@aednichols 

> How do I render configs from a personal non-develop branch of firecloud-develop? Realizing full well that those terms will change but the goal persists. Not a blocker tho.

Since the local development configuration now lives in the firecloud-ui repo and not firecloud-develop, you would make changes in your firecloud-ui PR, alongside corresponding code changes. Hope that helps!

**Comment by aednichols** [comment]
Sounds good – that is more convenient and less error-prone!

**Pull request merged**
