### PR TITLE
GAWB-688: Remove google billing project field on profile page

### PR DESCRIPTION
**Pull request by MatthewBemis**
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] **Submitter**: Tell tech lead that the PR exists if s/he wants to look at it
- [x] **Submitter**: Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [x] **Tech lead**: sign off
- [x] **LR**: sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [x] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: Check configuration files in Jenkins in case they need changes
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't 
  working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev server still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by MattPutnam** [comment]
:+1:?  I'm a little confused by this code, it appears that this field was never being used, along with a few others as well.

**Comment by davidangb** [comment]
There are model objects in orchestration that use billing account name (as Option[String]s, so they won't break). If this field is really going away, permanently, we should remove them from orchestration too.

**Comment by MatthewBemis** [comment]
@davidangb it seemed like it was going to be a permanent change, so I've opened the related orchestration PR here: https://github.com/broadinstitute/firecloud-orchestration/pull/220

**Comment by MattPutnam** [comment]
Oh I see, I misread how the fields were being saved.  Yeah, this is fine, just need the orch piece too.

**Comment by MattPutnam** [comment]
:+1:

**Pull request merged**
