### PR TITLE
Snapshot comments for methods & configs [GAWB-2032]

### PR DESCRIPTION
**Pull request by aednichols**
Requires https://github.com/broadinstitute/firecloud-orchestration/pull/507, https://github.com/broadinstitute/agora/pull/214

Illustrated guide to places where this is supported:

- Referenced method
screen shot 2017-10-04 at 5 01 36 pm

- Method import
screen shot 2017-10-04 at 5 00 15 pm

- Method detail
screen shot 2017-10-04 at 5 06 02 pm

- Config detail _(Per AC, no UI to add config snapshot comments at present; API only)_
screen shot 2017-10-04 at 4 27 49 pm

- Create new method
screen shot 2017-10-04 at 5 08 00 pm

- Clone method
screen shot 2017-10-04 at 5 07 41 pm

- Edit method
screen shot 2017-10-04 at 5 07 30 pm

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
Whaddya think about hiding the snapshot comment - at least on the config detail page - if it's empty? This might need PO/UX review. I'm thinking mostly about the case that comments are only available to the API, and therefore I'm guessing will be uncommon on configs. So for most configs we'll be showing an empty field, and that seems not ideal.

**Comment by aednichols** [comment]
Moran and I will discuss this. I'd actually vote to remove config snapshot comments from the UI entirely to avoid user confusion around where they come from (i.e. the API).

**Review by MattPutnam — APPROVED** [review]
👍 Code looks good, didn't test it

**Review by davidangb — APPROVED** [review]
:+1: code looks good to me. Did not test. I have the one question re: displaying snapshot comments, which you are following up on.

**Comment by aednichols** [comment]
Solution decided with Moran is to hide the entire snapshot comment field (label + value) for configs unless a comment actually exists. Documented the reason in a comment.

**Comment by aednichols** [comment]
jenkins retest

**Pull request merged**
