### PR TITLE
View and edit workspace ACL from UI

### PR DESCRIPTION
**Pull request by MattPutnam**
Note: this depends on the matching orchestration PR.

### CODE REVIEW

**Comment by MattPutnam** [comment]
Actually, now that I look at this closer there's some screwy behavior.  But I want to add this functionality sooner rather than later for dev purposes, so I'll keep this PR open.

**Comment by eddiebroad** [comment]
I loaded this with but then saw "Loading ACL..." and the spinner never went away....  Is that the "screwy" behavior that you're talking about?

**Comment by MattPutnam** [comment]
Good call on ACL vs. Permissions.  Will change to "permissions"

It should be working.  Try cleaning your build?

**Comment by MattPutnam** [comment]
See 2nd commit for updates.  Previously you could edit the text of an existing ACL entry which did weird things, and I wasn't handling the case of adding a new row but leaving it empty.  I'm much happier about this now.

**Comment by MattPutnam** [comment]
Update: Orchestration PR is in so this is good to go

**Comment by eddiebroad** [comment]
@MattPutnam I cleaned my build but still see the spinner and it doesn't go away.  That's with use-live-data=false .....  should I not use mock data?  Has anyone else gotten past the spinner I wonder...

**Comment by dmohs** [comment]
:+1: Code looks good. Works great! So awesome!

**Pull request merged**
