### PR TITLE
Iz compatible tables

### PR DESCRIPTION
**Pull request by zarsky-broad**

### CODE REVIEW

**Comment by zarsky-broad** [comment]
jenkins:retest

**Comment by davidangb** [comment]
Could you give details of what to look for, visually? I am not immediately noticing a difference.

**Comment by zarsky-broad** [comment]
In Chrome, there should be no visual difference. In Firefox, wide tables should behave better.

**Review by davidangb — APPROVED** [review]
:+1: I didn't do extensive testing, but this seems good.

**Review by MattPutnam — APPROVED** [review]
👍

**Pull request merged**
