### PR TITLE
adding checking for a code and message which may sometimes come from

### PR DESCRIPTION
**Pull request by eddiebroad**
AGORA

### CODE REVIEW

**Comment by MattPutnam** [comment]
Is this really a bug in Agora?  Should Agora be returning a more appropriate response code?

**Comment by eddiebroad** [comment]
@MattPutnam you have a good point.  When I issued/created this PR it was specifically with DSDEEPB-1239 in mind.  I wonder if @davidangb  would say that the subtask dsdeepb-1239 should be something for silver to address or for Agora to address.

**Comment by dmohs** [comment]
Agree with @MattPutnam. Our services have standardized on returning a 400+ HTTP status code on error. Let's close this PR once a bug has been filed against Agora.

**Comment by davidangb** [comment]
we need to isolate whether or not this is a bug in Agora or in orchestration layer. It is possible (I have no proof one way or another) that agora returns a 500 but orchestration layer returns 200.

**Comment by eddiebroad** [comment]
image

**Comment by eddiebroad** [comment]
I posted one case where an agora bug is seemingly manifested

**Comment by davidangb** [comment]
I discussed with Brad - they consider it a bug in agora if they return an http 200 with an error, and they believe they've fixed it (at least in dev). We should not add any special handling, which means we can close this. I'm closing it now.

**Pull request closed without merging**
