### PR TITLE
Split search entry values into individual key strokes. 

### PR DESCRIPTION
**Pull request by rushtong**
No Jira.

See swatomation failure case: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/3297/

I was able to reproduce this locally, but infrequently (roughly 1 in 10), on both of the `DataUseAwareSearchSpec."The ontology autocomplete exists and works"` ontology autocomplete test cases (`fatal` and `brux`). Current state is that the full search text value is entered into the autocomplete field all at once, but the autocomplete handler sometimes only recognizes one of the characters of the entered text. You can reproduce the swatomation failure screenshot by entering `f` into the disease search box on dev, even though the text entered in the failure case is the full string `fatal`. 

My solution is to enter the text one character at a time to make sure that the Autocomplete handler 
is triggered for each key. This better simulates manual data entry, and in local testing, has not failed. 

---

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
Swatomation failure is here: https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/1142/consoleFull
And looks unrelated to the change in this PR.
```
[info] *** 11 TESTS FAILED ***
[error] Failed: Total 132, Failed 11, Errors 0, Passed 121
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.user.ProfileSpec
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainSpec
```

**Review by aednichols — APPROVED** [review]
👍 LGTM

**Comment by rushtong** [comment]
Second swatomation run has more failures:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/1145/console
```
[info] *** 15 TESTS FAILED ***
[error] Failed: Total 132, Failed 15, Errors 0, Passed 117
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainSpec
[error] 	org.broadinstitute.dsde.firecloud.test.workspace.WorkspaceSpec
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodConfigSpec
```

**Review by aweng98 — APPROVED** [review]
👍good solution.

**Comment by rushtong** [comment]
Latest swatomation failures are all `AuthDomainSpec` failures:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/1166/consoleFull
```
[error] Failed: Total 132, Failed 10, Errors 0, Passed 122
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainSpec
```

**Comment by aweng98** [comment]
can you try this to approve a point? rerun jenkin job but revert your change first? let's see if these many test failures still happen. I suspect so many failures are caused by one char typing at a time.
either you don't have latest UI tests fixes or this change is causing new failures that we haven't see before.

**Comment by aweng98** [comment]
I'm testing this locally. give me few hours to investigate.

**Comment by rushtong** [comment]
Currently testing Alex's theory. Reverted back to dev and running swatomation.
Run: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/3339/

**Comment by aweng98** [comment]
this is what happened that failed tests. text value was entered twice in search field. 
`AuthDomainSpec_revoke_70b75812-7a60-43fe-ac1e-f39c043fc273AuthDomainSpec_revoke_70b75812-7a60-43fe-ac1e-f39c043fc273`

**Comment by rushtong** [comment]
Thanks @aweng98 - this PR doesn't solve anything then. Will close.

**Pull request closed without merging**
