### PR TITLE
View WDL and other method details when viewing a selected MC (from in a user workspace not method repo)

### PR DESCRIPTION
**Pull request by eddiebroad**
by having the WDL in view when in a selected MC:
1)  you don't have to go to the method repo to know the WDL
2)  the WDL, being known to the user, tells the user what the MC will do upon launch/execution

### CODE REVIEW

**Comment by MattPutnam** [comment]
Instead of doing this, we should use the EntityDetails component.

**Comment by eddiebroad** [comment]
@MattPutnam I had thought to use that in the gray area above (where there is the render-top-bar) but then the expandable/collapsable text pushes everything under it up and down so that's why I thought to put the viewer down below, so that it doesn't make stuff under it go up and down (cause there's nothing much under it!)

**Comment by MattPutnam** [comment]
What I mean is, completely replace `render-top-bar` with the component.

**Comment by eddiebroad** [comment]
@MattPutnam  Re : "What I mean is, completely replace render-top-bar with the component."
If the collapsable/exapandable WDL is there, then everything below the top-bar can go up/down depending on the WDL being collapsed/expanded.  Is that really desired?

**Comment by MattPutnam** [comment]
I don't think it's a bad thing.  That's already how the method repo works.

**Comment by eddiebroad** [comment]
I put the EntityDetail viewer at the top-bar now

**Comment by davidangb** [comment]
Please recreate this PR against develop!

**Pull request closed without merging**
