### PR TITLE
GAWB-3063 Use webpack for static files in ui

### PR DESCRIPTION
**Pull request by zarsky-broad**
Twinned with https://github.com/broadinstitute/firecloud-develop/pull/926

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by zarsky-broad** [comment]
jenkins retest

**Comment by zarsky-broad** [comment]
jenkins retest

**Comment by zarsky-broad** [comment]
jenkins retest

**Review by MattPutnam — COMMENTED** [review]
This is a pretty big ¯\\\_(ツ)\_/¯ from me. Seems legit?

**Comment by davidangb** [comment]
I'm always wary of comprehensive changes like this, such as updating a bunch of dependencies, but it all seems to work. Could I confirm a few things?

* previously, we had compiled.js and base-deps.bundle.js. These are now combined into base-deps.bundle.js. Correct?
* I see slightly different file sizes on this branch vs. dev branch for markdown-deps.bundle.js, codemirror-deps.bundle.js, and igv-deps.bundle.js. Why is this? Is this due changes in uglify?

**Comment by zarsky-broad** [comment]
1. The files are bundled together now, right. This way we (1) cut out another network request, and (2) have a clearer demarcation of responsibilities, where everything that's loaded in the browser passes through webpack, either because it's in static or because it's required in deps.

2. That's what I would expect, yes, as that's the only change that touches them.

**Comment by zarsky-broad** [comment]
The exception to no. 1 is in dev builds, where figwheel stages the files that it is in charge of hot-reloading directly into public, as having webpack move the build folder led to hot reloads always being one behind, due to the delay.

**Review by davidangb — APPROVED** [review]
:+1: okay, approving, on the assumption that you've thoroughly tested it, and can get automated tests to pass.

**Comment by zarsky-broad** [comment]
jenkins retest

**Comment by zarsky-broad** [comment]
The only failure was in the OrchestrationApiSpec; as there's no Orchestration change as part of this PR, I'm counting these tests as passed.

**Review by dmohs — APPROVED** [review]
Changes look good. I also loaded this up and changed some code and index.html. Expected behavior. 👍

**Pull request merged**
