### PR TITLE
refactor gcs preview and call-orch

### PR DESCRIPTION
**Pull request by davidangb**
This is PR 1 of 2 (or maybe 3) towards removing storage scopes from the UI. This PR has two refactors/tweaks:

## ajax.cljs
I factored out (most of) the duplication between `call-orch` and `call-leo`, driven because I want to add a `call-sam`. This should be functionally equivalent, purely a code refactor.

## gcs_file_preview.cljs
I streamlined and tweaked the GCS Preview modal.

Previously, the modal *always* made two ajax calls:
1. get metadata for the object
2. get the last 20k bytes of the object to power the text preview

And then only displayed the text preview if the first call succeeded and if the object in question passed a filename filter. This is easily visible if you monitor ajax calls in dev tools.

As of this PR, the modal:
* gets metadata for the object
* if and only if the metadata call succeeds and the object passes the filename filters, make another call to get the last 20k bytes, and display those bytes.

I've also tweaked which files show previews a little bit, and factored out the logic for what's previewable:
* always show preview for anything that is text/plain or application/json
* don't show preview for pdf

Finally, while the preview content is loading, I have added a spinner where previously we showed "..." text.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
this passed UI tests on the first commit. I'm about to commit unit tests, which will trigger another swat run (but unit tests should have zero effect on swat runs)

**Comment by jmthibault79** [comment]
How likely are we to see a misconfigured content-type, like a BAM with text/plain?

**Review by ghost — APPROVED** [review]
Tested! Looks good 👍

**Review by jmthibault79 — APPROVED** [review]

**Comment by davidangb** [comment]
@jmthibault79 I think we're unlikely to see a misconfigured content type, though it's possible - so I wanted to handle the case!

**Comment by davidangb** [comment]
second round of swat tests failed on TSV errors: `TSV parsing error: no header` which is known flaky. Given the first round passed, I'm calling this good.

**Pull request merged**
