### PR TITLE
GAWB-1119: re-enable lists/numbers for library metadata

### PR DESCRIPTION
**Pull request by davidangb**
part of GAWB-1119, but doesn't necessarily fix it all the way. Still need support for booleans, eventually.
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  - Acceptance criteria exists and is met
  - Note any changes to implementation from the description
  - Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  - Authentication
  - Authorization
  - Encryption
  - Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- Review cycle:
  - LR reviews
  - Rest of team may comment on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH
  - Submitter updates documentation as needed
  - Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by MattPutnam** [comment]
I can't save library attributes at all right now.

**Comment by davidangb** [comment]
Ah, I should have stated this right up front, was going too fast - if you're getting errors on saving metadata, make sure you're running against broadinstitute/firecloud-orchestration#280.

Once on that branch ... I see metadata being saved, and I see metadata sent back in the ajax responses, but I do _not_ see the metadata displayed in the UI. Not sure why yet.

**Comment by MattPutnam** [comment]
Got it working.  👍

**Comment by skwalker** [comment]
👍  lgtm

**Comment by rushtong** [comment]
👍 Re-tested - looks good.

**Comment by rushtong** [comment]
Got the 👍 from hipchat

**Pull request merged**
